// Trips
export const SET_SEARCH_CITIES = 'SET_SEARCH_CITIES';
export const SELECTED_CITY_STATE = 'SELECTED_CITY_STATE';

// Navigation
export const SET_TAB = 'SET_TAB';
// Page State
export const LIST_RECOMMENDED_CITIES = 'LIST_RECOMMENDED_CITIES';
export const SET_SEARCH_BAR_STATE = 'SET_SEARCH_BAR_STATE';